#!/bin/sh /etc/rc.common
# "new(er)" style init script
# Look at /lib/functions/service.sh on a running system for explanations of what other SERVICE_
# options you can use, and when you might want them.

START=85
CONFIG=https-dns-proxy
SBIN=/usr/sbin/https-dns-proxy
SERVICE_DAEMONIZE=1

start() {
	config_load $CONFIG
	config_foreach handle_config https-dns-proxy
}

stop() {
	service_stop $SBIN
}

xappend() { 
	param="$param $1"; 
}

append_param() {
	local section="$1"
	local option="$2"
	local switch="$3"
	local default="$4"
	local _loctmp
	config_get _loctmp "$section" "$option" "$default"
	[ -z "$_loctmp" ] && return 0
	xappend "$switch $_loctmp"
}

handle_config() {
	local section=$1
	local param

	append_param $section "listen_addr" "-a" "127.0.0.1"
	append_param $section "listen_port" "-p" "1053"
	append_param $section "user" "-u" "nobody"
	append_param $section "group" "-g" "nogroup"
	append_param $section "dns_servers" "-b" ""
	append_param $section "resolver_url" "-r" ""
	append_param $section "subnet_addr" "-e" ""
	append_param $section "proxy_server" "-t" ""
	append_param $section "logfile" "-l" ""
	append_param $section "other_flag" "" ""
	
	service_start $SBIN $param
}

